### ISSUE TITLE
[FEATURE](All modules) <Collapse table view>

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#110]
By default when arriving on a module, show both tables (Baseline and Endline) collapsed. with just the total co2 visible.

**Comment by charlottegiseleweil** [comment]
@ctobin111 we're plannnig to do this ok ?

**Comment by guilbep** [comment]
I'm not convinced :) tell me what you think @charlottegiseleweil  @ctobin111  ?
Before:
<img width="1735" alt="before" src="https://user-images.githubusercontent.com/161889/229052427-5e34b0ec-8269-4618-96fe-e4d4b89b325e.png">

After:
[new-collapse.webm](https://user-images.githubusercontent.com/161889/229053303-ab9f0ae5-6633-4942-bac4-f62381ec7950.webm)

**Comment by charlottegiseleweil** [comment]
I find it better when you arrive that you can directly compare the baseline/endline results, which is impossible when the tables get huge. Perhaps could be clarified with keeping the headers not collapased, so it's clear that it's an expandable table ?

**Comment by ctobin111** [comment]
@charlottegiseleweil @guilbep I think it is better to see the data or at least the first first rows of the data to understand that data is indeed within the table. I will be adding in another design feature request as Charlie knows. UNHCR has asked that specific endlines (when there are multiple endlines for one baseline) can be check-marked or chosen so that these are considered the best interventions for comparison with the baselines in the final change in emission calculations. This would be a priority. Charlie and I agreed that this would be better suited as a change for all modules by mid-May. (A heads up Pierre :)

**Comment by guilbep** [comment]
Thank you @ctobin111 @charlottegiseleweil . I won't ship as is then. It's not easily doable with our current ui-framework. (at least 1 day of work instead of 30mn like above).
We'll discuss it a bit more later in April then.

Thank you for the heads-up Cara!

**Comment by charlottegiseleweil** [comment]
Ok moving this to milestone 2.2 is good then !

**Comment by guilbep** [comment]
@ctobin111 we didn't ship that feature; do we want to do it ? or do I trash it ? (it was done in march. and has been waiting ever since)

**Comment by ctobin111** [comment]
@guilbep This was not one of their recent list of complete comments. So, I am closing this.
