### ISSUE TITLE
Change Column view to Table view

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#111]
The Wash screen should change to a table views (like Energy-Facilities)
It should work directly for water, WasteWater and Sludge (it's the type of trucking)
- New transport button

## Columns are :
 - Trucking Type (input)
 - Distance (btwn camp and water source) (input)
 - Volume Total (totale volume of water collected) (input)
 - Volume Truck in m3 (input)
 - Type of Truck (Diesel/Petroleum) (input)
 ### Calculated columns
- Total co2
- Total distance
- number of trucks used 
 
## two tables
- Baseline
- Endline
### having the total co2 emissions at the end

Turn this module to table view :
<img width="955" alt="Screenshot 2022-10-17 at 10 22 17" src="https://user-images.githubusercontent.com/18381609/196126166-ed844144-359f-4aa9-a405-8ad9746690bc.png">

**Comment by ctobin111** [comment]
@guilbep Our WASH UNHCR meeting on Friday indicated that the calculated value of 'Number of trucks used' when calculating with km input is not very useful to them. If you have already implemented it, no worries, otherwise, please do not waste the time.

Very important: when implementing this new structure for litres used as the input, the inputs and outputs are much simpler:

### Columns are :

**Inputs column**
Trucking Type (input)
Litres used (input)
Type of Truck (Diesel/Petroleum) (input)

**Calculated column**
Total co2 (output)

Please contact me with Jabber if you have any questions.

Thank you
