### ISSUE TITLE
[FIX](Reference DB): fix 'Use only the factors in this table in the Reference DB'

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Hi Pierre,

I see that the previous reference factors were not deleted. Can you kindly only include the factors in this Excel attached? If there is an issue with the previous code and the updated factors, let me know so that I can confirm that we are using the correct updated factors everywhere.

Thank you!

[EMISSION FACTORS FUELS FACILITIES AND WASH TRUCKING.xlsx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/10267188/EMISSION.FACTORS.FUELS.FACILITIES.AND.WASH.TRUCKING.xlsx)

**Comment by guilbep** [comment]
@ctobin111 The only change I see is for REF_WSH_D
I just have 0.25213 for REF_WSH_D instead of 0.25 ? is that the only change ?
Could you possibly just edit the csv here ? and version it when you change the values? https://docs.google.com/spreadsheets/d/1kcXiaCU6SLSFZh4qT8jyyi2R3b6AYK-lxeEdCRRUW68/edit#gid=2140645093

It's a copy of this file: https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/blob/main/couchdb/rawdata/ghg_reference.csv which I used to fill in the database

**Comment by guilbep** [comment]
done in release v0.5.4. I'm closing this issue @ctobin111 please reopen if it's still not correct
