### ISSUE TITLE
[FEATURE] <GHG warnings when baseline and endline do not match>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#184]
@guilbep Could you kindly put the red warning (e.g., This comparison is not valid because baseline and endline have different energy demands and the warnings for WASH trucking and cookstoves) at the bottom under the endline?

UNHCR requested this today after the demo: insert the warning "endline and baseline do not match" not at the top (with the baseline) but at the bottom (with the endline). Otherwise users might not see it

**Comment by guilbep** [comment]
@ctobin111 I think You're talking about the energy - facilities module ? since it's already the case of trucking ?
<img width="1403" alt="total_volume_pumped" src="https://user-images.githubusercontent.com/161889/210811367-0416f607-c743-4f48-a7f7-5b05ecba7a86.png">
cf screen shot ? or is it ? If what we have in the screenshot does not correspond to what you expect please advise.

**Comment by guilbep** [comment]
<img width="1434" alt="faciliti@ctobin111"  src="https://user-images.githubusercontent.com/161889/210816166-1d5a983b-532c-4eec-b4f2-5c093c17d7e1.png">
@ctobin111  for facilities I moved it here. Please confirm it's okay. I'll wait before pushing to production
