### ISSUE TITLE
[FEATURE] <General Page GHG>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#251]
@guilbep UNHCR has asked:

Is it necessary to fill in all information to be able to save a new assessment or can we provide default values (e.g., number of people per HH) so that it is not necessary to fill in unknown data?

For a default number of people per household, we can say 5.

**Comment by charlottegiseleweil** [comment]
Option 1 
- Values are not required in GNRL INFO tab BUT the modules that need these values get disabled if value is missing. (with a hover explaining "this module is disabled because xxxx missing value in Information tab" (see how it's done in Shelter tool).

Option 2 
- We can do what you suggested - Just note that this default value will then be used in the Facilities equations. Is that ok ?
We then recommend to add a little (i) Hover box explaining where this default value comes from...
- The value is not required, but we then use a default value in calculations. Need text with reference for  (i) Hover box explaining where this default value comes from...
Let us know what you choose ?

**Comment by ctobin111** [comment]
@charlottegiseleweil 

@guilbep 

UNHCR has requested that default values are automatically added if nothing is provided because those values are needed for calculations. We could have the same warning as shelter so that they know that they must agree on the default values otherwise they cannot access the modules.

This option 2 is best for us: Recommend a (i) Hover box explaining where the default values come from and that it can be overwritten.

1) Solar Day Hours default can come from the GHG Solar Average database that Pierre cleverly created, preferably the default can be linked per country.

2) Household default can come from this database:
https://docs.google.com/spreadsheets/d/1TON2WR45tJlsfpA1tPvltDNq8TpbUJLr/edit?usp=sharing&ouid=110398523820759855394&rtpof=true&sd=true
Reference: https://www.un.org/development/desa/pd/data/household-size-and-composition

@guilbep can the HH size per country be aggregated easily by you as you did in the case of solar?

**Comment by guilbep** [comment]
@ctobin111 could you do the aggregation/provide me the default value for households per country ? If not I'll just put '4'

**Comment by guilbep** [comment]
Okay for now. Decided with @ctobin111 that we will look into the average solar cookstove after wednesday

**Comment by guilbep** [comment]
done in b065f9c fix(ghg): default values
