### ISSUE TITLE
[POLISH] Refactor front-end - remove left menu 

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#285]
merge Apps + About in "Home" (accessible through house tab instead or 2 lines on top left)
merge Logout/User
so the left menu bar becomes useless :)

**Comment by guilbep** [comment]
<img width="1693" alt="looks_like_this" src="https://user-images.githubusercontent.com/161889/229054122-8ddfc04c-ddf3-49bc-b825-18ee79f38854.png">

**Comment by guilbep** [comment]
done in [9e82ce1](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/commit/9e82ce1719c80f01a6629b52b92544aae5fbf9fa)

 
Add heading textAdd bold text, <Cmd+b>Add italic text, <Cmd+i>
Add a quote, <Cmd+Shift+.>Add code, <Cmd+e>Add a link, <Cmd+k>
Add a bulleted list, <Cmd+Shift+8>Add a numbered list, <Cmd+Shift+7>Add a task list, <Cmd+Shift+l>
Directly mention a user or team
Reference an issue, pull request, or discussion
Add saved reply
Slash commands
Leave a comment
No file chosen
Attach files by dragging & dropping, selecting or pasting them.
Styling with Markdown is supported
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/blob/d25efaa0f7b3cf36f8785c3afb60cb9b9f84bab4/CONTRIBUTING.md) and [code of conduct](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/blob/d25efaa0f7b3cf36f8785c3afb60cb9b9f84bab4/CODE_OF_CONDUCT.md).
Assignees
@[guilbep](https://github.com/guilbep)
guilbep
Labels
[common](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/labels/common)
Scope: concern all the app regardless of ghg/shelter or others
Projects
[ UNHCR - TSS](https://github.com/orgs/EPFL-ENAC/projects/13)

Milestone
[Release 1.0](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/milestone/16)
Development
When branches are created from issues, their pull requests are automatically linked.

[polish/285-refactor-front-end-remove-left-menu](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/tree/polish/285-refactor-front-end-remove-left-menu)
[EPFL-ENAC/unhcr-geneva-tech-hub-app](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app)
Notifications
Customize
You’re receiving notifications because you are watching issues on this repository.
2 participants
@guilbep
@charlottegiseleweil
 
 Delete issue
