### ISSUE TITLE
[GHG General] <Placement and functionality of warnings>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#308]
@guilbep 

For the release of the Facilities and WASH trucking to the field, this is one of two changes that UNHCR would like to see:

- [ ]	Error message not appearing when energy consumption in the baseline is different from the one in the endline if this error message has already been clicked and removed before.
- [ ] It was recommended to give a more prominent place to the warning message.
- [x] Can the message be put in between the baseline and endline or on top of the endline interventions?
- [ ] Valerio and Manuel suggested having a pop-up box that must be closed or accepted to be able to continue the assessment. 
- [ ] The comment about the differences in energy consumption must remain.

**Comment by guilbep** [comment]
@ctobin111  ? One of two changes ? What's the second one ?

**Comment by guilbep** [comment]
@charlottegiseleweil Since it appears like it's mandatory before the testing in the field. I'll release that today also.
Hoping it's not worst than before. 🗡️ 
Also @ctobin111 When you have several points/questions could you make several bullets points. 

Since I'm not sure how to display/ not display the warning. I'll always show the warning. I don't think it's a problem per your 'requirements'. since it's non-blocking, and that users are able to continue.
<img width="1737" alt="I'llputitthere" src="https://user-images.githubusercontent.com/161889/229139927-5b17644e-9083-46bf-a68f-86624c86e7cd.png">

**Comment by guilbep** [comment]
done in 167e316] fix(ghg): display warning all the time

by the way, it's supposed to be a warning. But we put it as an 'alert' in red because of readability. Maybe the problem is that orange was not readable enough
You can choose with those variants: https://v2.vuetifyjs.com/en/components/alerts/#colored-border
<img width="982" alt="test" src="https://user-images.githubusercontent.com/161889/229140453-f111d794-6b79-49ba-8504-e2f3770ff614.png">
