### ISSUE TITLE
[GHG General] <Give new name to duplicated data in Baseline>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@guilbep We noticed when demonstrating the tool that when you click on the duplicate in the baseline, the name of the baseline is the same and it cannot be edited. Ideally, each time a new baseline is provided a new name such as Name_1 and then Name_2 and then Name_3 could be provided and that it could be editable.

Here is a screenshot of the current problem of duplicating in the baseline for all modules.

![image](https://user-images.githubusercontent.com/111510926/229076647-e3f98174-e1af-4611-a891-ed6d9a265a24.png)

Thank you,

Cara

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
Hey @ctobin111 I can edit the name. Are you sure you're not able to do so ? I see nothing in the code responsible for the behavior your experiencing.

I can change the current behavior to add a suffix each time. It'll take me some time though. I will put that in phase 2.2 since For me it's not a bug (since I cannot reproduce it)

**Comment by guilbep** [comment]
I'll add a 'copy' at the end if the name exist.
That's what I can do in such sort notice
<img width="633" alt="copy_" src="https://user-images.githubusercontent.com/161889/229143699-559ac556-6e85-40e6-844e-11b9f2566dce.png">

**Comment by guilbep** [comment]
done in fe603ee (HEAD -> dev, origin/dev) fix(ghg): add suffix for duplicated items
