### ISSUE TITLE
[FEATURE] <GHG> intro tutorial

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#380]
Do something like: https://introjs.com/docs/getting-started/install

To present the ghg/shelter tool and it's documentation.

- new button in login popup (first time)
- steps:
   - highlight the question mark
   - tbd....

**Comment by guilbep** [comment]
André is not interested

**Comment by ctobin111** [comment]
@guilbep We will need more feedback from UNHCR on this but finishing the modules and their revisions is the priority.

**Comment by guilbep** [comment]
Closing the issue due to no-activity or news from UNHCR on this; Please open it again @ctobin111 if it's part of the needed features.

**Comment by ctobin111** [comment]
@guilbep yes, I think UNHCR will want to do this in January.

**Comment by guilbep** [comment]
@ctobin111 What's the status of this issue ?

**Comment by ctobin111** [comment]
@guilbep This was not requested by UNHCR to date. It is a cool intro idea so that we can welcome the users to the tool so that they know how to find the user's manual, etc. They would only see this during their initial login. I am happy to create a video but do you really think that this can be implemented in time? I will be busy the next 2 weeks with re-doing the videos and updating the Guidance Manuel. We will have new fNRB and Grid Factor csv files to upload.

**Comment by guilbep** [comment]
- not enough time to implement
- no spec
guidance manuel and videos are enough
