### ISSUE TITLE
[FEATURE] <GHG Wash trucking monthly data>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#400]
@guilbep Can we convert all input data to monthly for WASH trucking since water is generally only trucked for the first months for emergency purposes. By then a borehole is normally found. The monthly input would obviously be multipled by 12 to get to annual.

**Comment by guilbep** [comment]
It'd be good to finish this in august in feeback

**Comment by guilbep** [comment]
<img width="1735" alt="diff_between_month_and_year2" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/a1dda9d7-f771-4ddb-b757-e881b9c2fdc4">
<img width="1737" alt="diff_between_month_and_year" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/0572513c-448c-4e54-b607-4939df597fd0">


I'm pretty sure that due to approximation of the number of trucks:

 truck number  = Math.ceil(volumeCollected / Truck volume);

We have a small discrepencies when moving away from the '/year' to the '/month' logic.


I'm merging and deploying to the test platform so you can have a look @ctobin111 @nmontoya03
