### ISSUE TITLE
[FIX](GHG Cooking): fix 'Zero change in emissions shown in red'

### ISSUE THREAD

**Issue by nmontoya03** [EPFL-ENAC/unhcr-geneva-tech-hub-app#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

This is a Manuel's comment from his feedback on 21/07/2023:

No change (e.g. in cookstove usage, fuel or household percentages) obviously leads to zero change in emissions, but the zero is displayed in red (cf. screenshot below, first line of endline scenario)

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/a0f91583-c730-4a74-9552-1431c87a733c)
![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/33e7b883-3cd4-43d7-ae99-f5a04366f489)

@guilbep Could you please check this issue? Thank you!

**Comment by guilbep** [comment]
@nmontoya03 @ctobin111 I don't have the url in the issue. So it's quite difficult to debug.

But my guess is that the CO2 is something like -0.0003 (that's why it's red); We have a maximal number of decimal to display of two(per the spec). So when we format the number it becomes: 0.

It would help to have the url.


But I'm not sure how I should fix this, since it's not a bug.. it's just that we're not displaying the real number... maybe we should have a 'tooltip info box' that gives the real number without truncating the decimal ? What do you think @nmontoya03  @ctobin111  ?
