### ISSUE TITLE
[FIX](GHG): fix 'unchanged total population for new assessments'

### ISSUE THREAD

**Issue by nmontoya03** [EPFL-ENAC/unhcr-geneva-tech-hub-app#424]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Expected Behavior

This is a Manuel's comment from his feedback on 21/07/2023:

Total population: I have manipulated a population figure in the past (Mauritania / Mbera: 5 people  &  5 people per household; cf. image below). When now opening a new assessment and using again the existing site “Mbera” (created based on UNHCR data), the manipulated population figure still appears (5 people). It would be good that when setting a new assessment, the initially provided population figure would be provided (as provided by UNHCR).

![Screenshot_2023-08-21-14-23-00(1)](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/58d64a44-49c0-44f2-b00c-3e848a3fe9e8)

@guilbep could you please check this option? Thank you!

**Comment by guilbep** [comment]
Well. It's not a bug.. It's a feature. All assessment are sharing the same information page (it's because it's the same site). That's how we designed it back in the day

@nmontoya03 @ctobin111 We should either explain it more clearly to the user. Or having completely different setup for each assessment. It's not clear on my side. 

Please advise.

**Comment by guilbep** [comment]
done
