### ISSUE TITLE
[FIX](GHG): fix 'show results of all the modules in results page'

### ISSUE THREAD

**Issue by nmontoya03** [EPFL-ENAC/unhcr-geneva-tech-hub-app#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

I added information for the Facilities, Lighting and Solid Waste modules but only the emissions from Lighting are visible in the results page (please see the example in the screenshot and url below).
https://unhcr-tss.epfl.ch/green_house_gaz/JO/1641/surveys/b7c88be7-6f6b-4764-8ee2-ccaa4f3445e1?category=Results

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/131168517/481d74e8-778c-4e78-8272-1610c581d912)

@guilbep could you please check this? Thank you!

**Comment by guilbep** [comment]
@nmontoya03 @ctobin111 my intuition is that it's because it's 57TCo2 eq vs 60000 and the graph is not showing the data properly because its too small like comparing a kilometer and a meter; as you can see; It's possible to see the facilities: ![facilities](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/4c3791a0-2e0a-45d8-bf6d-6143fb220089)
It's just not practical.. We could probably use a log scale if it happens too often?
![problem](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/55287f9c-69c3-4702-92a2-5dc5f10aae84)



Since I 'found out' why. I'm closing this issue. Please re-open with a comment if you think it's necessary
