### ISSUE TITLE
[BUG] create new assessment with UNHCR account

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#48]
When logged in with UNHCR login : 
Steps to reproduce :
Create new assessment in existing site Or 
Either behavior (a) ASSESSMENT IS EMPTY ! >> Page blanche (reproduced by @blueur with site in Algeria)
Or behavior (b) When Energy > Facilities > Don't have writing rights, doesn't save created site. (reproduced by @blueur with site in Jordan)

-- Had previously thought it's a user rights scheme issue - disregards convo below.
Based on UNHCR August feedback to Cara - in particular comments in 3.1, review the user rights scheme
[220718 Generic review UNHCR-TSS app_facilities cooking.docx](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/files/9373797/220718.Generic.review.UNHCR-TSS.app_facilities.cooking.docx)

**Comment by ctobin111** [comment]
I spoke with UNHCR this morning and their issue is that when they try to add a new assessment to an existing site in Facilities, such as Kenya Kukuma, they get this Read Only message. Please see the screenshot attached. Basically, we all agreed that anyone should be able to add in new assessments to an existing site. The assessments themselves should have the same users, thus limited access. This is normal for the field since assessment creators may change over the years. Different users can create different endlines over the years for instance. I hope this can be done. 
![image](https://user-images.githubusercontent.com/111510926/185890936-d5b84623-dcb2-4c6f-b010-f55f73756db6.png)

**Comment by charlottegiseleweil** [comment]
Steps to reproduce : 
Create new assessment in existing site > Then add new Facilities.

@blueur try to reproduce with UNHCR login.
@ctobin111 ask s.o else at UNHCR to try to reproduce . 

Cara + Charlie didn't experience the bug when reproducing.

**Comment by guilbep** [comment]
- Maybe we should forbid changing the site name; it may  conflicts with existing sites.

**Comment by ctobin111** [comment]
Hi Pierre,

Yes, changing site names should not be allowed.

Best,

Cara

________________________________

**Comment by guilbep** [comment]
Marking this issue as closed!
