### ISSUE TITLE
[FEATURE][GHG]Module: Cooking c

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#487]
<b>comment</b>: Carbonized vs. non-carbonized briquettes: Using a traditional cookstove, GHG emission increase by 280% when switching from non-carbonized to carbonized briquettes – please check whether this is correct.<br/><b>actions</b>: null<br/><hr/><b>estimated_hours</b>: 0.5<br/><b>unhcr_comments</b>: null<br/><b>ctobin111</b>: null<br/><b>me</b>: "Update databases with received info"

**Comment by guilbep** [comment]
@ctobin111 @nmontoya03 What's the status of this issue ?

**Comment by nmontoya03** [comment]
Default value for carbonized briquettes needs to be updated based on its net calorific value (which is different to the one of non-carbonized briquettes). Currently both carbonized and non-carbonized briquettes are using the same default consumption whereas they have different energy content. @guilbep @ctobin111 Closing this issue since the default value is being updated with the default values database mentioned on issue https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/issues/608
