### ISSUE TITLE
[BUG] <Scorecard not functioning>

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Other shelters don't appear in the scorecard (along axes)

<img width="1624" alt="Screenshot 2024-02-26 at 09 46 30" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/108796343/a7e97657-3d6c-4275-89b4-1b311849ede6">

### Expected Behavior

All completed shelters should appear (I think as dots, and the current shelter is distinguished as a diamond)

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
<img width="1789" alt="scorecard" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/3bd59f2e-de6b-47c1-96b9-613eb12edd0a">
<img width="1488" alt="acted" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/7c2d031f-d3ac-4879-abe6-6f967d59a4c3">

<img width="1682" alt="compare" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/161889/4e6613eb-6550-4046-bdf2-db53a2ba58d0">
The problem was that we didn't have any completed shelter.
I'm closing @andreullal, you can reopen if you want to discuss how to improve this
