### ISSUE TITLE
[BUG] <login-automatic logout-can't login again>

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

To login, I needed t change my password. After some time, I was automatically logged out. When I tried to login again, my new password didn't work - I had to reset the password again.

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment]
Hi André,

- I highly probably reseted your password when deploying a new version to production, that's why you could not logged in
- After 24h, you're automatically logged out, if it was a shorter time period, we need to check why, but this authentication method is going to disapear, we're only going to use unhcr login system
- I probably reseted your password between both actions., if that's not the case let's discuss that on monday.

Anyway, since this authentication method is going to the bin, we're probably good with this.

Thanks for opening an issue, and let's discuss about it again on monday just to be sure
