### ISSUE TITLE
Aggregation and analysis of project assessment data

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#88]
"greater impact on improving shelter sustainability can be achieved by developing further functions that enable the aggregation and reporting of shelter assessment data, that support comparison and analysis of shelter assessment results..."

**Comment by charlottegiseleweil** [comment]
@andreullal Precisions needed to implement this tab

- In the summary data, how are we aggregating over all shelters - sum or averages?
- Do you have a correspondence between countries and UNHCR regions ? (we only have the info at country-level at this stage)

This summary report will be available under the "overview" tab, rather than where you showed it - because it's not common to all apps, so it needs to be within the shelter app.

**Comment by andreullal** [comment]
@charlottegiseleweil 

For summary data, it should be averages/means
For regions, I've reached out to UNHCR for region/country lists - will get back to you

**Comment by guilbep** [comment]
![IMG_7100](https://user-images.githubusercontent.com/161889/212123470-99872bb4-526b-4afd-9c29-605b40ecac7b.jpg)

**Comment by guilbep** [comment]
cf #164 for the latest design
